[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
datastorePreferencesAndroid = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
retrofit = "3.0.0"
interceptor = "5.3.2"
hiltAndroidCompiler = "2.59"
runner = "1.7.0"
ksp = "2.3.4"
secrets = "2.0.1"
navigationFragment = "2.9.6"
glide = "5.0.5"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences-android = { module = "androidx.datastore:datastore-preferences-android", version.ref = "datastorePreferencesAndroid" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferencesAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
#Interceptor
interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "interceptor"}
# Dagger Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
#NavigationComp
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
#Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
#Hilt
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidCompiler" }
#Secrets
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
#KSP
devtools-ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
#SafeArgs
safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationFragment" }

